### PR TITLE
feature(nyz): add new middleware distributed demo

### PR DESCRIPTION
**Pull request by PaParaZz1**
## Description

- [x] DataParallel demo
- [x] DistributedDataParallel demo
- [x] tb logger example 
- [x] Distributed RL demo (Ape-X type)

## Related Issue
#102 
#176 

## Check List

- [ ] merge the latest version source branch/repo, and resolve all the conflicts
- [ ] pass style check
- [ ] pass all the tests

### CODE REVIEW

**Comment by zxzzz0** [comment]
What is the throughput of this? Does this beat SampleFactory? @PaParaZz1 @sailxjx

**Comment by sailxjx** [comment]
@zxzzz0 This is not to compare the speed with sample factory, because you know that the bottleneck of RL training may appear in any one of the collecting, training, and evaluation, for example, too fast collecting may lead to too much generation difference and underfitting of the model, and because of the existence of GIL, the deserialization of data on the training process will also slow down the overall training efficiency, and there are many points that we need to consider in this project. 
This issue will provide a new design pattern for global RL training, starting from the idea that users can easily scale from single-computer studies to large-scale distributed systems without very large code modification costs or performance losses.
If you are really very very concerned about environment-side collecting, then you can use sample factory inside the di-engine to achieve the collecting efficiency you expect.

**Comment by zxzzz0** [comment]
>If you are really very very concerned about environment-side collecting

No. To clarify, we only care about **overall** performance, which means the time it will take to reach certain reward in the end. 

Usually if you can squeeze every drop of performance out of the CPU/GPU, you can learn faster. Environment-side collecting is just one indicator and there are many other indicators as well. You will also have to pay attention to the learner FPS, GPU utilization and other indicators for you to understand the throughput of the whole system.

When doing benchmarking, it's not targeted for the collector side but the overall growth speed of reward.

**Comment by sailxjx** [comment]
> No. To clarify, we only care about overall performance, which means the time it will take to reach certain reward in the end.

Yeah, that's right, the purpose of the distributed version is to maximize overall performance while not requiring too much effort to write code on multiple tasks.

Another consideration is that we need to go design-first. Only after the upper layer interface is unified and stable, it will be possible to gradually optimize all aspects of performance without disturbing the user. You can see that from version 0.x to version 1.0, we have gradually developed a definite interface style [example](https://github.com/opendilab/DI-engine/blob/main/ding/example/dqn.py), and the purpose of this branch is to extend this interface style to distributed operation.

**Pull request merged**
