### PR TITLE
fix(mahuangxu): data collection errors caused by shallow copies

### PR DESCRIPTION
**Pull request by mahuangxu**
## Description
_def collect_ in sample_serial_collector.py seems wrong cause shallow copies of variable "self._traj_buffer" and "obs". 
Shallow copies of "obs" will result in s and s' saved in the buffer being the same. Shallow copies of "self._traj_buffer" will result in unmatched states and actions.

## TODO
Deepcopy added to  variable "self._traj_buffer" and "obs". On this basis, the function of _def to_tensor_transitions_ in base_serial_collector.py is simplified.

## Check List

- [x] merge the latest version source branch/repo, and resolve all the conflicts
- [x] pass style check
- [x] pass all the tests

### CODE REVIEW

**Comment by PaParaZz1** [comment]
please maintain the same commit and PR format

**Comment by mahuangxu** [comment]
> By default, we use shallow copy to save memory cost of replay buffer and deepcopy time, maybe you can modify this function as a switch. And I want to know the specific bug case you meet, do you modify `s` when training phase?

1. Variable "obs" in def collect of sample_serial_collector.py: 
I use debug tool to test in my own env. and found that when Line 12 step into a new environment state, 'obs' of Line 1 will change and then the latest obs saved in 'self._obs_pool' will change.
```
1                obs = self._env.ready_obs
2                # obs = copy.deepcopy(self._env.ready_obs)  # avoide shallow copy  
3                # Policy forward.
4                self._obs_pool.update(obs)
5                if self._transform_obs:
6                    obs = to_tensor(obs, dtype=torch.float32)
7                policy_output = self._policy.forward(obs, **policy_kwargs)
8                self._policy_output_pool.update(policy_output)
9                # Interact with env.
10              actions = {env_id: output['action'] for env_id, output in policy_output.items()}
11              actions = to_ndarray(actions)
12              timesteps = self._env.step(actions)
```

**Comment by mahuangxu** [comment]
> By default, we use shallow copy to save memory cost of replay buffer and deepcopy time, maybe you can modify this function as a switch. And I want to know the specific bug case you meet, do you modify `s` when training phase?

2. Variable "self._traj_buffer" in def collect of sample_serial_collector.py:
I find that in the loop 'for env_id, timestep in timesteps.items():', the observation state of "self._traj_buffer" of the last of each cycle and which of the beginning of the next cycle are different. This bug can be solved by deepcopy.

**Comment by PaParaZz1** [comment]
> > By default, we use shallow copy to save memory cost of replay buffer and deepcopy time, maybe you can modify this function as a switch. And I want to know the specific bug case you meet, do you modify `s` when training phase?
> 
> 1. Variable "obs" in _def collect_ of sample_serial_collector.py:
>    I use debug tool to test in my own env. and found that when Line 12 step into a new environment state, 'obs' of Line 1 will change and then the latest obs saved in 'self._obs_pool' will change.
> 
> ```
> 1                obs = self._env.ready_obs
> 2                # obs = copy.deepcopy(self._env.ready_obs)  # avoide shallow copy  
> 3                # Policy forward.
> 4                self._obs_pool.update(obs)
> 5                if self._transform_obs:
> 6                    obs = to_tensor(obs, dtype=torch.float32)
> 7                policy_output = self._policy.forward(obs, **policy_kwargs)
> 8                self._policy_output_pool.update(policy_output)
> 9                # Interact with env.
> 10              actions = {env_id: output['action'] for env_id, output in policy_output.items()}
> 11              actions = to_ndarray(actions)
> 12              timesteps = self._env.step(actions)
> ```
> 
> After solving this bug, _def to_tensor_transitions_ in base_serial_collector.py, _def to_tensor_transitions_ in base_serial_collector.py can be simplified. Because "transition = self._policy.process_transition( self._obs_pool[env_id], self._policy_output_pool[env_id], timestep )" in _def collect_ of sample_serial_collector.py can bind the obs of the previous step with the state of the current step after action, no further processing is required by function to_tensor_transitions.

I guess the bug you meet is because there are some overlap parts in `s_t` and `s_t+1` of environment. And I will add a `deepcopy` switch to solve your problem.

**Review by PaParaZz1 — APPROVED** [review]

**Comment by PaParaZz1** [comment]
@mahuangxu I polish related code in #475, could you review and test whether the current implementation solves your problem?

**Pull request merged**
