### PR TITLE
adapt unittest to github actions

### PR DESCRIPTION
**Pull request by PaParaZz1**
- fix DinvEnvWrapper test bug
 - add rerun in test_ppg and test_demo_buffer
 - fix coverage ignore problem
 - add upload coverage

### CODE REVIEW

**Comment by HansBug** [comment]
Well, I'm asking for the privilege of codecov in order to visit the coverage information for this repo. (btw, I usually use coverall to do this).

**Comment by HansBug** [comment]
And, considered that some of the code test can not run well in github action (especially tests on cuda environment), you can try to create your own runner. See this page: https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners

**Comment by PaParaZz1** [comment]
> And, considered that some of the code test can not run well in github action (especially tests on cuda environment), you can try to create your own runner. See this page: https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners

It's a good point. But unfortunately, we don't have proper GPU machine in public network.

**Comment by HansBug** [comment]
> > And, considered that some of the code test can not run well in github action (especially tests on cuda environment), you can try to create your own runner. See this page: https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners
> 
> It's a good point. But unfortunately, we don't have proper GPU machine in public network.

Emmm, pity of this. We'd to find a way to get one or more gpu machine which can be accessed by public network (attention, in public network is not necessary, access-abled is okay), the default runner probabaly cannot support gpu-based or heavy-cpu-based calculation.

**Pull request merged**
