### PR TITLE
feature(nyz): add gobigger baseline

### PR DESCRIPTION
**Pull request by PaParaZz1**
## Description

add baseline for [GoBigger environment](https://github.com/opendilab/GoBigger)

image

DQN + naive self-play + structured obs

Screen Shot 2021-10-14 at 10 11 58 PM

DQN + naive self-play + structured obs + spatial obs
Screen Shot 2021-10-17 at 5 18 44 PM

## Check List

- [x] merge the latest version source branch/repo, and resolve all the conflicts
- [ ] pass style check
- [ ] pass all the tests

### CODE REVIEW

**Comment by zxzzz0** [comment]
What does `structed obs` mean? Is this a new feature supported by opendilab?

**Comment by PaParaZz1** [comment]
> What does `structed obs` mean? Is this a new feature supported by opendilab?

sorry for the typo, it means scalar information + unit information, like a **structured dict**, you can refer to [here](https://github.com/opendilab/DI-engine/blob/dev-gobigger-baseline/dizoo/gobigger/envs/gobigger_env.py#L86)

**Comment by jayyoung0802** [comment]
1. Why self-play  use [DQNPolicy, RandomPolicy] not use [DQNPolicy,DQNPolicy]?
2. Experiment with petrel_tracing,  functions  such as Server.step_state_tick、GoBiggerEnv.obs_transform  and Server.spwan_balls  take a lot of time.  Details view https://confluence.sensetime.com/display/~yangzhenjie/Gobigger+Profile

**Comment by jayyoung0802** [comment]
Hi @zxzzz0,
Speed measurement analysis:
1. command : ding -m serial -c cartpole_a2c_config.py -s 0
2. The key function is serial_pipeline() in ./ding/entry/serial_entry.py.
3. The speed measurement results and the corresponding codes of each time module are as follows:
4. In summary, initialization, and establishment(replay_buffer, env, policy collector) take a lot of time. And the first time collecting data and training data takes a lot of time.

image
image
image

**Comment by zxzzz0** [comment]
@jayyoung0802 Thank you so much! 


It looks like that `collector.collect` and `learner.train` take majority of the time. Making these two running in parallel will lead to at least 2x speed up. @PaParaZz1 What do you think?

**Pull request merged**
