### PR TITLE
fix(i-am-tc): Import errors after running setup.py, edited version numbers 

### PR DESCRIPTION
**Pull request by i-am-tc**
## Description

I am using gitpod.io service + VS code as my IDE. Forked out only yesterday. Discovered this import error in the process of creating mountain car environment

First I got this : see https://is.gd/ft2Vmu for jinja2 import of escape
Second I got this: see https://is.gd/gXsTrh for markupsafe import error.

This commit got rid of import errors.

Unfortunately, I only have a screenshot of the jinja2 import error.

image

## Check List

- [ ] merge the latest version source branch/repo, and resolve all the conflicts
- [ ] pass style check
- [ ] pass all the tests

### CODE REVIEW

**Comment by PaParaZz1** [comment]
Can you modify the name format of pull request, like what mentioned in our developer [doc](https://di-engine-docs.readthedocs.io/en/latest/24_cooperation/git_guide.html#git-commit-specification)

**Comment by PaParaZz1** [comment]
For this bug, can you provide the specific version of `jinjia2` and `markupsafe` which lead to the error you meet?

**Comment by i-am-tc** [comment]
> Can you modify the name format of pull request, like what mentioned in our developer [doc](https://di-engine-docs.readthedocs.io/en/latest/24_cooperation/git_guide.html#git-commit-specification)

Hello! My bad for missing out on the git commit documentation. I was looking to close the loop on submitting a PR at least once to work out the kinks. 

I had renamed this PR as per below. 

image

**Comment by i-am-tc** [comment]
> For this bug, can you provide the specific version of `jinja2` and `markupsafe` which lead to the error you meet?

The original setup.py installed jinja2 that is version 3.1.2. This gave rise to "ImportError: cannot import name 'escape' from 'jinja2'"

Having traced the problem, it looks like support for escape module was dropped in recent version of JInja. Source [here](https://stackoverflow.com/questions/71718167/importerror-cannot-import-name-escape-from-jinja2)

When I adjusted setup.py to "jinja2<3.1.0" , it installed version 3.0.3. That took care of "ImportError: cannot import name 'escape' from 'jinja2'"

To repeat the error

1. Go to [this](https://gitpod.io/start/#opendilab-diengine-fnzyawavrz2) . This will require you to connect your GitHub with GitPod. This link leads you to a docker instance of VS code with DI-engine already in it (that things sits on an EPYC processor). I had installed GitPod browser extension and so it was just a click away to spawn the instance. Note the gitpod button to the right. 

I close the sharing on the instance once we sort out this PR. 

image

3. Once you're in the instance, run python setup.py install 

4. Then, run python testing_pr_448.py ; You should see the error. This python file holds the import I was trying to use while constructing the env for mountain car.

5. If I do a pip uninstall jinja2 followed by a pip install jinja2==3.0.3 , and then run (4) again, the import problem goes away. 

For some reason, I cannot replicate the markupsafe import error. It seemed to have just gone away. So that should ignored for now. 

The jinja2 import error seems more consistent.

**Review by PaParaZz1 — APPROVED** [review]

**Comment by i-am-tc** [comment]
Reading GitPod's documentation https://is.gd/LziOud , and it seems I should have shared the URL of the snapshot of my original instance, not the URl for source instance itself.

This should be the link. 

https://gitpod.io#snapshot/9670cb3e-a587-45a1-92e5-6a8318b4c263

**Pull request merged**
