### PR TITLE
feature(i-am-tc) : Mountain Car & Rainbow 

### PR DESCRIPTION
**Pull request by i-am-tc**
## Description

Use rainbow algorithm on mountan car environment.

I intend for this branch to hold mountain car + Rainbow work. 

## Check List

- [ ] merge the latest version source branch/repo, and resolve all the conflicts
- [ ] pass style check
- [ ] pass all the tests

### CODE REVIEW

**Comment by i-am-tc** [comment]
Commit [c33f464](https://github.com/opendilab/DI-engine/pull/471/commits/c33f464542a2bee93a9e4e27b3747140ce29d3e9) can be made to run if nstep is set to 1 (i.e. checkpoint files observed to be generated). When nstep is set to anything >1 , error below shows up

When using serial pipeline , the config file works as it should, regardless of nstep value, i.e. able to train

Unlike using serial pipeline, using task does not seem to write log messages to folder "logs"

Screenshot_20220903-184840_Samsung Internet

**Comment by i-am-tc** [comment]
Useful comments on config file fields by @PaParaZz1 from #452 

Screenshot_20220904-170657_Firefox

**Comment by i-am-tc** [comment]
[7522e6d](https://github.com/opendilab/DI-engine/pull/471/commits/7522e6d54e21c0479bafe2b45b6211a4e5916131)

With reference to commit above:

Whenever I change max_workers to be more than 1 or async = True, I get the following error

Still trying to debug.

image

**Comment by i-am-tc** [comment]
Removed LightTuner portion from [7522e6d](https://github.com/opendilab/DI-engine/pull/471/commits/7522e6d54e21c0479bafe2b45b6211a4e5916131) (i.e. as per DI-engine docs code example), turned on async, got error below

Screenshot_20220911_130918

**Comment by PaParaZz1** [comment]
This PR will be reopened in future version

**Pull request closed without merging**
